project/bboard/urls.py
from django.urls import path
from .views import PostListView, PostDetail, PostEdit, PostCreate, PostDelete, CommentSearchView, CommentView, \
    AddComment, CommentFormView, comment_del, change_status

app_name = 'bboard'
urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('<int:pk>/', PostDetail.as_view(), name='detail'),
    path('commform/', CommentFormView.as_view(), name='comment_form'),
    path('create/', PostCreate.as_view(), name='create'),
    path('edit/<int:pk>/', PostEdit.as_view(), name='edit'),
    path('delete/<int:pk>/', PostDelete.as_view(), name='delete'),
    path('comm/', CommentSearchView.as_view(), name='comments'),
    path('comment/<int:pk>/', CommentView.as_view(), name='comment'),
    path('add_comm/', AddComment.as_view(), name='add_comment'),  # ad-comment
    path('comm/delete/<int:com_pk>/', comment_del, name='del_comm'),
    path('change/<int:com_pk>/', change_status, name='change_status')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bboard.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import *

app_name = 'users'
urlpatterns = [
    path('login/',
         LoginUser.as_view(), name='login'),
    path('logout/',
         LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('signup/',
         BaseRegisterView.as_view(template_name='users/signup.html'), name='signup'),
    path('next/', view_code, name='log_next'),
    path('next/code/', log_with_code_view, name='view_code')
]

project/bboard/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth import get_user_model
from ckeditor_uploader.fields import RichTextUploadingField


User = get_user_model()


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='Автор')

    CAT = {
        ('Tanks', 'Танки'),
        ('Heals', 'Хилы'),
        ('Damage dealers', 'ДД'),
        ('Dealers', 'Торговцы'),
        ('Guild masters', 'Гилдмастеры'),
        ('Quest givers', 'Квестгиверы'),
        ('Blacksmiths', 'Кузнецы'),
        ('Leatherworkers', 'Кожевники'),
        ('Potion masters', 'Зельевары'),
        ('Spell masters', 'Мастера заклинаний')
    }

    cat = models.CharField(max_length=22, choices=CAT, verbose_name='Категория')
    title = models.CharField(max_length=256, verbose_name='Заголовок', blank=True)
    content = RichTextUploadingField(default='', verbose_name='Текст поста')
    datetime_creation = models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')
    image = models.ImageField(upload_to='images/%Y/%m/%d/', default=None, verbose_name='Картинка поста', blank=True)
    time_update = models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')
    is_published = models.BooleanField(default=True)

    # @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

    def preview(self):
        return self.content[0:123] + '...'

    def __str__(self):
        return f'№:{self.pk}, текст: {self.title} -{self.content[0:123]}'

    def get_absolute_url(self):
        return f'/{self.pk}'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments', verbose_name='К посту')
    author = models.ForeignKey('auth.user', on_delete=models.CASCADE, verbose_name='Автор отклика')
    text = models.TextField(verbose_name='Комментарий')
    datetime_creation = models.DateTimeField(auto_now_add=True)
    accepted = models.BooleanField(default=False, blank=True, verbose_name='Коммент принят')
    
    def get_absolute_url(self):
        return reverse('comment', kwargs={'pk': self.pk})

    def __str__(self):
        return f'No{self.pk} - {self.author}--{self.text}'

    def is_accepted(self):
        if True:
            self.accepted = True
        else:
            self.accepted = False   # self.rejected = True
        return self.instance

project/bboard/forms.py
from django import forms
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.exceptions import ValidationError
from django.forms import ModelForm, BooleanField, CharField, Form, Textarea, TextInput

from .models import Post, Comment


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        # self.fields['cat'] = forms.ModelChoiceField(label='Пост', empty_label='ghj')

    class Meta:
        model = Post
        fields = ('title', 'cat', 'content', 'image',)
        widgets = {'title': forms.TextInput(attrs={'size': '80'}),
                   'image': forms.FileInput(attrs={'size': '40'}),
                   }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['text'].label = 'Отклик'


class CommentAddForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("text", "author", "post")

    def __init__(self, *args, **kwargs):
        super(CommentAddForm, self).__init__(*args, **kwargs)
        self.fields['text'].label = 'Новый отклик'

project/bboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponseNotFound, HttpResponseRedirect, HttpResponsePermanentRedirect

from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, View, DeleteView, FormView
from .filters import PostFilter, CommentFilter
from .forms import PostForm, CommentForm, CommentAddForm
from .models import Post, Comment
from .utils import DataMixin


class PostListView(ListView):
    model = Post
    template_name = 'bboard/post_list.html'  # post_list.html'
    context_object_name = 'posts'
    ordering = ['-datetime_creation']
    form = PostForm
    paginate_by = 4

    def get_queryset(self):
        queryset = PostFilter(self.request.GET, super().get_queryset()).qs
        # фильтрация queryset-ом
        return queryset

    def get_context_data(self, **kwargs):  # забираем отфильтрованные
        # объекты переопределяя метод get_context_data у
        # наследуемого класса - полиморфизм
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())
        return context


class PostDetail(DataMixin, DetailView):  # DataMixin
    model = Post  # модель всё та же, но мы хотим получать детали конкретно отдельного товара
    template_name = 'bboard/detail.html'
    queryset = Post.objects.all()
    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        context['form'] = CommentAddForm
        return context

class CommentFormView(FormView):
    form_class = CommentForm
    success_url = '/'  # '/'

    def form_valid(self, form, *args, **kwargs):
        form.instanse.post = self.kwargs.get('pk')
        form.instance.post_id = self.kwargs['post_pk']
        form.instance.user = self.request.user
        self.object = form.save()
        return super(CommentFormView, self).form_valid(form)


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'bboard/post_create.html'
    form_class = PostForm
    # permission_required = ('bboard.create',)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = User.objects.get(id=self.request.user.id)
        post.save()
        return redirect('/')


class PostEdit(DataMixin, UpdateView):  # DataMixin, IsAuthorMixin
    model = Post
    form_class = PostForm
    template_name = 'bboard/post_edit.html'
    context_object_name = 'post'
    success_url = '/'

    # get_object вместо queryset для получения инфо об obj редактирования
    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)

    def form_valid(self, form):
        messages.success(self.request, 'Запись успешно обновлена!')
        return super().form_valid(form)


class PostDelete(DeleteView):  # PermissionRequiredMixin
    template_name = 'bboard/delete.html'
    queryset = Post.objects.all()
    success_url = '/'
    permission_required = ('bboard.delete',)

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)


class CommentSearchView(DataMixin, ListView):  # DataMixin
    """replies for using in account"""
    model = Comment
    template_name = 'bboard/comments.html'  # v 'bboard/my_comments.html' v 'bboard/comments.html'
    context_object_name = 'comments'  # 'finded_comments'
    ordering = '-datetime_creation'
    # permission_required = ('comment')
    paginate_by = 5

    def get_queryset(self):
        queryset = CommentFilter(self.request.GET, super().get_queryset()).qs  # фильтрация queryset-ом
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = CommentFilter(self.request.GET, queryset=self.get_queryset())
        # вписываем наш фильтр в контекст
        return context

    # def get_context_data(self, **kwargs):  # забираем отфильтрованные объекты переопределяя метод get_context_data
    #     # у наследуемого класса - полиморфизм
    #     context = super().get_context_data(**kwargs)
    #     user_id = self.request.user.id
    #     context['filter'] = CommentFilter(self.request.GET, queryset=self.get_queryset())
    #     context['new_comment'] = Comment.objects.filter(post__author=user_id).filter(rejected=False).filter(accepted=False)
    #     context['del_comment'] = Comment.objects.filter(post__author=user_id).filter(rejected=True)
    #     context['add_comment'] = Comment.objects.filter(post__author=user_id).filter(accepted=True)
    #     return context


class CommentView(DetailView):  #DataMixin
    """detail of reply"""
    model = Comment
    template_name = 'bboard/comment.html'
    context_object_name = 'comment'
    paginate_by = 4


class AddComment(DataMixin, CreateView):   # LoginRequiredMixin, DataMixin
    """ for add reply at details"""
    model = Comment
    form_class = CommentAddForm
    context_object_name = 'comment'
    ordering = ['datetime_creation']
    template_name = 'bboard/add_comment.html'
    # permission_required = ('bboard.add_comment')
    success_url = '/comm'


class CommentAccepted(DataMixin, View):  # IsAuthorMixin
    def get(self, request, *args, **kwargs):
        com_pk = kwargs['com_pk']

        comment = Comment.objects.get(pk=com_pk)
        comment.accepted = True
        comment.save()

        return redirect(request.META['HTTP_REFERER'])


class CommentRejected(DataMixin, View):  # IsAuthorMixin
    def get(self, request, *args, **kwargs):
        com_pk = kwargs['com_pk']

        comment = Comment.objects.get(pk=com_pk)
        comment.accepted = False
        comment.save()

        return redirect(request.META['HTTP_REFERER'])


def comment_del(request, com_pk):
    comment = get_object_or_404(Comment, pk=com_pk)
    comment.delete()
    return redirect('bboard:comments')


def change_status(request, com_pk):
    """Change status of comments"""
    comment = get_object_or_404(Comment, pk=com_pk)
    comment.accepted = False if comment.accepted else True
    comment.save()
    return redirect('bboard:comments')


def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')

project/templates/bboard/add_comment.html
{% block content %}

    <h3>Добавление коммента</h3><br>

	{% if user.is_authenticated %}
	<form method="POST" name="add" >
		{% csrf_token %}
        {{ form }}
		<input class="btn btn-secondary" type="submit" value="Добавить комментарий">
	</form><br>
	{% endif %}

    <a href="/">Назад ко всем объявлениям</a>
{% endblock %}

project/templates/bboard/comm_del.html
{% extends 'base.html' %}
 
{% block title %} Comment delete {% endblock title %}
 
{% block content %}
<h4>Вы действительно хотите удалить данный комментрий?</h4>
<table>
    <thead>
        <th width="230">Пост</th>
        <th width="155">Дата отклика</th>
        <th width="80">Автор отклика</th>
        <th width="330">Коммент</th>
    </thead>
    {% for comment in filter.qs %}
        <tr>
            <td><p align="left">{{ comment.post|striptags }}</p></td>
            <td><p align="left">{{ comment.datetime_creation }}</p></td>
            <td><p align="left">{{ comment.author.username }}</p></td>
            <td><p align="left">{{ comment.text|censor|striptags }}</p></td>
        <td>
</table>
<br>
<br>
 
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="подтвердить"></form>
    <br>
    <a href="/"> Все посты </a>
{% endblock content %}

project/templates/bboard/commentToMail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Появился новый отклик на ваш пост {{ comment.post.title }}</h2>
<p>{{ comment.author }} откликнулся на ваш пост.</p>
<p>Перейдите по <a href="http://127.0.0.1:8000/comm">ссылке</a> для выполнения действий.</p>
</body>
</html>

project/templates/bboard/commentToMailUpdated.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2> {{ user }},
    Статус вашего отклика к посту "{{ comment.post.title }}" обновлен.</h2>
<p>
    Пользователь
    {% if comment.accepted %}
        принял ваш комментарий "{{ comment.text }}" на его пост.
    {% else %}
        отклонил ваш комментарий "{{ comment.text }}" на его пост.
    {% endif %}
</p>
</body>
</html>

project/templates/bboard/comments.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title %} Comments {% endblock title %}

{% block content %}

    <h4> Отклики </h4>
    {% if filter.qs %}
        <form method="GET" name="comments">
            {{ filter.form }}
            <input class="btn btn-outline-danger" type="submit" value="Поиск по откликам">
        </form><br>

        <a href='/comm'> очистить </a><br>

        <table cellpadding="1" frame="hsides">
            <caption align="top"> <h4>Комменты на посты:</h4></caption>
                <tr>
                    <th width="230">Пост</th>
                    <th width="155">Дата отклика</th>
                    <th width="80">Автор отклика</th>
                    <th width="330">Коммент</th>
                    <th>Действия с откликом - Принять или Отклонить, а можно и Удалить</th>
                </tr>
                {% for comment in comments %}
                <tr>
                    <td><p align="left">{{ comment.post|striptags }}</p></td>
                    <td><p align="left">{{ comment.datetime_creation }}</p></td>
                    <td><p align="left">{{ comment.author.username }}</p></td>
                    <td><p align="left">{{ comment.text|censor|striptags }}</p></td>
                    <td>
                        {% if comment.accepted %}
                            <a href="{% url 'bboard:change_status' comment.pk %}" title='Изменить на "Отклонить"'>Отклонить</a>
                        {% else %}
                            <a href="{% url 'bboard:change_status' comment.pk %}" title='Изменить на "Принять"'>Принять коммент</a>
                        {% endif %}
                    </td>
                    <td>
                        <form action="{% url 'bboard:del_comm' comment.pk %}" method="delete">
                            <button>Удалить</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
        </table>
    {% else %}
        <h5> Откликов пока нет... </h5>
        <a href='/comm'> <br> Очистить фильтр </a><br>

    {% endif %}

{% include 'bboard/pagination.html' %}

{% endblock content %}

project/templates/bboard/delete.html
{% extends 'base.html' %}
 
{% block title %} Post delete {% endblock title %}
 
{% block content %}
<h4>Вы действительно хотите удалить данный пост?</h4>
<table>
    <thead>
        <th width="80">Автор</th>
        <th width="130">Заголовок</th>
        <th width="200">дата публикации</th>
        <th>Текст</th>
    </thead>
    <tr>
        <td>{{ post.author|title }}</td>
        <td>{{ post.title }}</td>
        <td>{{ post.datetime_creation }}</td>
        <td>{{ post.preview|striptags }}</td>
    </tr>
</table>
<br>
<br>
 
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="подтвердить"></form>
    <br>
    <a href="/"> Все посты </a>
{% endblock content %}

project/templates/bboard/detail.html
{% extends 'base.html' %}

{% load custom_filters %}

{% block content %}

    <h5> Информация о выбранном посте </h5>

    <div class="details">
        Автор поста: <span class="author"><strong><em>{{ post.author }}</em> </strong></span><br>
        Заголовок: <span class="text"> <strong> {{ post.title|censor }} </strong> </span><br>
        Пост опубликован: <span class="date"> <strong> {{ post.datetime_creation|date:'d M Y H:m' }} </strong> </span><br>
        Текст поста: <span class="date"> <strong> {{ post.content|censor|striptags }} </strong> </span><br>

        {% if post.image %}
            <div class="col">
                Фото: <span class="image"> <strong> {{ post.image }} </strong></span>
                <img src="{{ post.image.url }}" class="card-img-left" width="25%">
            </div>
        {% endif %}
        <br>
    </div>
    <hr>

    {% if user.is_authenticated %}
    <h5> Здесь можно добавить комментарий к посту {{ post.author }} версии от {{ post.time_update }}</h5>
    <form enctype="multipart/form-data"
          method="post"
          action="{% url 'bboard:add_comment' %}">
        {% csrf_token %}
        <input type="hidden" name="post" id="post_id" value="{{post.id}}">
        <input type="hidden" name="author" id="user_id" value="{{user.id}}">
        {% comment %} <input type="hidden" name="text" id="text_id" value="{{text.id}}"> {% endcomment %}
        <textarea type="hidden" name="text" class="form-control" value="" rows="3"></textarea>
        {% comment %}  <div class="col-auto"></div> {% endcomment %}
        <input class="btn btn-outline-info" type="submit" value="подтвердить">
    </form>
    {% endif %}
    <input type=button value="Назад" class="btn btn-outline-secondary" onClick="javascript:history.go(-1);">

    <a href="/"> Все посты </a><br>

    {% include 'bboard/pagination.html' %}

{% endblock %}

project/templates/bboard/index.html
{% extends 'base.html' %}

{% block content %}
<ul class="list-articles">
	{% for p in posts %}
		<li>
			<div class="article-panel">
				<p class="first">Категория: {{ p.category.name }}</p>
				<p class="last">Дата: {{ p.time_update|date:"d-m-Y H:i:s" }}</p>
			</div>

			<h2>{{ p.title }}</h2>
			{% if p.image %}
				<p><img class="img-article-left thumb" src="{{ p.image.url }}"></p>
			{% endif %}

			{% autoescape off %}
				{{p.text|linebreaks|truncatewords:50}}
			{% endautoescape %}

			<div class="clear"></div>
			<p class="link-read-post">
				<a href="{{ p.get_absolute_url }}">Читать пост</a>
				{% if user == p.user and user.is_authenticated %}
					<a href="{% url 'update_post' p.slug %}" style="background-color: #0f74a8">Редактировать</a>
				{% endif %}
			</p>
		</li>
	{% endfor %}
</ul>
{% endblock %}

project/templates/bboard/my_comments.html
{% extends 'base.html' %}

{% block title %}
    Reply
{% endblock title %}

{% block content %}

<br>
<form method="GET">
    {{ filter.form }}
    <input type="submit" value="Найти">
</form><br>

<hr>

{% if new_comment %}
    <br><h3>Новые отклики</h3><br>
    <table cellspacing="5" cellpadding="10" border="1"
       style=" border-spacing : 10px; border-color : blue; border-style: solid;" bgcolor="FFFFFF">
        <tr>
            <td width="300"><h5>Объявление</h5></td>
            <td width="100"><h5>Пользователь</h5></td>
            <td width="250"><h5>Отклик</h5></td>
            <td width="150"><h5>Дата отклика</h5></td>
            <td width="250"><h5>Действия</h5></td>
        </tr>
        {% for com in new_comment %}
            <tr>
                <td><p align="center">{{ comment.post }}</p></td>
                <td><p align="center">{{ comment.author }}</p></td>
                <td><p align="center">{{ comment.text }}</p></td>
                <td><p align="center">{{ comment.datetime_creation | date:"d M Y" }}</p></td>
                <td><p align="center"><a href="{% url 'accept' comment.id %}"><u>принять</u></a> / <a href="{% url 'reject' comment.id %}"><u>отклонить</u></a></p></td>
            </tr>
        {% endfor %}
    </table><br>

{% else %}
    <h3>Новых откликов нет</h3><br>
{% endif %}

{% if add_comment %}
    <br><h3>Принятые отклики</h3><br>
    <table cellspacing="5" cellpadding="10" border="1"
           style=" border-spacing : 10px; border-color : blue; border-style: solid;" bgcolor="FFFFFF">
        <tr>
            <td width="300"><h5>Объявление</h5></td>
            <td width="100"><h5>Пользователь</h5></td>
            <td width="250"><h5>Отклик</h5></td>
            <td width="150"><h5>Дата отклика</h5></td>
            <td width="250"><h5>Статус</h5></td>
        </tr>
        {% for comment in add_comment %}
        <tr>
            <td><p align="center">{{ comment.post }}</p></td>
            <td><p align="center">{{ comment.author }} </p></td>
            <td><p align="center">{{ comment.text }}</p></td>
            <td><p align="center">{{ comment.date_creation | date:"d M Y" }}</p></td>
            <td><p align="center">принят (<a href="{% url 'bboard/reject' comment.id %}"><u>отклонить</u></a>)</p></td>
        </tr>
        {% endfor %}
    </table><br>
{% endif %}

{% if del_comment %}

<br><h3>Отклоненные отклики</h3><br>
<table cellspacing="5" cellpadding="10" border="1"
       style=" border-spacing : 10px; border-color : blue; border-style: solid;" bgcolor="FFFFFF">
    <tr>
        <td width="300"><h5>Объявление</h5></td>
        <td width="100"><h5>Пользователь</h5></td>
        <td width="250"><h5>Отклик</h5></td>
        <td width="150"><h5>Дата отклика</h5></td>
        <td width="250"><h5>Статус</h5></td>
    </tr>
    {% for repl in del_comment %}
    <tr>
        <td><p align="center">{{ comment.post }}</p></td>
        <td><p align="center">{{ comment.author.username }} </p></td>
        <td><p align="center">{{ comment.text }}</p></td>
        <td><p align="center">{{ comment.datetime_creation | date:"d M Y" }}</p></td>
        <td><p align="center">отклонен (<a href="{% url 'bboard:accept' comment.id %}"><u>принять</u></a>)</p></td>
    </tr>
    {% endfor %}
</table><br>

{% endif %}

{% endblock content %}

project/templates/bboard/pagination.html
{% block pagination %}

{% if is_paginated %}

    {% if page_obj.has_previous %}
        <a href="?page=1">Первая</a>
        <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a>{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    <!-- Если есть следующая страница, то даём ссылку на неё и на самую последнюю страницу -->
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">>>></a>
        <a href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
    {% endif %}
{% endif %}

{% endblock pagination %}

project/templates/bboard/post.html
{% extends 'base.html' %}
{% load bboard_tags %}
 
{% block content %}
 
<h1>{{post.title}}</h1>
 
{% if post.image %}
  <p><img class="img-article-left" src="{{post.image.url}}"></p>
{% endif %}

{% autoescape off %}
    {{post.text|linebreaks}}
{% endautoescape %}

{% if request.user.is_authenticated %}
    <div class="clear"></div>
    <p class="link-read-post"><a href="{% url 'add_reply' post.slug %}">Добавить отклик</a></p>
{% endif %}

<h3>Отклики и комментарии:</h3>
<hr>
{% show_replies post_id=post.id %}

{% endblock %}

project/templates/bboard/post_create.html
{% extends 'base.html' %}

{% block title %} Create post{% endblock title %}

{% block content %}

    <h3>Добавить объявление </h3><br>
	<form method="POST" name="create" enctype="multipart/form-data" >
		{% csrf_token %}
		{{ form.media }}
        {{ form.as_p }}
		<input class="btn btn-outline-danger mt-2 float-center" type="submit" value="Добавить пост">
	</form><br>
Или
<input type=button value="Вернуться назад" class="btn btn-outline-warning mt-3" rows="2" onClick="javascript:history.go(-1);"><br>

<a href="/">А можно перейти ко всем объявлениям</a>

{% endblock content %}

project/templates/bboard/post_edit.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}

{% block title %} edit {% endblock %}

{% block content %}

<h3>Редактирование публикации</h3>

<!--Дата публикации: {{ post.dateCreated|date:'d-m-Y H:i' }}-->

<!-- Форма для добавления -->
<form method="POST" name="edit" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <input type="submit" value="Добавить статью">
</form>
<a href="/">Назад ко всем статьям</a>  <br>

{% endblock %}

project/templates/bboard/post_list.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title %} Post {% endblock title %}

{% block content %}

<div>
    <h4> Поиск </h4>
    {% if filter.qs %}
<!--        <h4>Найдено постов {{ filter.qs|length }} </h4>-->
        <form method="GET">
            {{ filter.form }}
            <input class="btn btn-outline-success" type="submit" value="Найти">
        </form>
        <h6><p> ** Чтобы оставить свой комментарий перейдите, пожалуйста, на страницу конкретного поста, нажав на заголовок...</p></h6>
        <a href="/"> очистить </a>
        <br>
        <table>
            <thead>
                <th width="350"> Заголовок </th>
                <th width="125"> Автор </th>
                <th width="130"> Категория </th>
                <th width="380"> Текст </th>
                <th width="180"> Опубликовано </th>
            </thead>
            {% for post in posts %}
                <tr>
                    <td>
                        <a href="{% url 'bboard:detail' post.id  %}"> {{ post.title|censor }}</a>
                        {% if user.is_authenticated %}
                            <a href="{% url 'bboard:edit' post.id %}"> Редактировать </a>
                            <a href="{% url 'bboard:delete' post.id %}"> Удалить </a>
                        {% endif %}
                    </td>
                    <td> {{ post.author }} </td>
                    <td> {{ post.cat }} </td>
                    <td> {{ post.content|censor|striptags }} </td>
                    <td> {{ post.time_update }} </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <h5>Пока ничего нечего не найдено, но вы можете попробовать позже. </h5>
        <a href="/"> очистить фильтр </a>
    {% endif %}
</div>

<br>
{% if user.is_authenticated %}
    <a href='create'> Добавить пост </a> <br>

    <a href="add_comment"> Оставить отклик </a> <br>
{% endif %}
<br>
<br>

{% include 'bboard/pagination.html' %}

{% endblock %}