project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bboard.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import *

app_name = 'users'
urlpatterns = [
    path('login/',
         LoginUser.as_view(), name='login'),
    path('logout/',
         LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('signup/',
         BaseRegisterView.as_view(template_name='users/signup.html'), name='signup'),
    path('next/', view_code, name='log_next'),
    path('next/code/', log_with_code_view, name='view_code')
]

project/users/models.py
from django.contrib.auth.models import User
from django.db import models


class OneTimeCode(models.Model):
    code = models.CharField(max_length=30, null=True, verbose_name="Код")
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True, verbose_name="Код")

    def __str__(self):
        return self.code

    # def get_absolute_url(self):
    #     return f'/{self.id}'

    class Meta:
        verbose_name = 'Временный код'
        verbose_name_plural = 'Временные коды'

project/users/forms.py
from allauth.account.forms import SignupForm
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError

from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django import forms


class EmailVerifyForm(forms.Form):
    code = forms.CharField(max_length=12, label='одноразовый код')


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))


class NewUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class OneTimeCodeForm(forms.Form):
    username = forms.CharField(max_length=30)
    code = forms.CharField(max_length=30)

project/users/views.py
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login, authenticate
from django.contrib import messages
from .forms import RegisterUserForm, LoginUserForm, OneTimeCodeForm, NewUserChangeForm
from .models import OneTimeCode

import random

# Create your views here.

class BaseRegisterView(CreateView):
    model = User
    form_class = RegisterUserForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('/')

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get('username')
        pasw = form.cleaned_data.get('password1')
        email = form.cleaned_data.get('email')
        user = authenticate(username=username, password=pasw)
        OneTimeCode.objects.filter(user=user).delete()
        code = ''.join(random.choice('0123456789abcdefghijklmnopqrstuvwxyzCDEFGHIJKLMNOPQRSTUVWXYZ') for i in range(6))
        OneTimeCode.objects.create(code=code, user=user)
        code = OneTimeCode.objects.get(user=user)
        print(user.email)
        send_mail("Сообщение",
                  "Имя пользователя:{}, пароль:{}".format(user.username, code.code),
                  from_email='g1.f4g@yandex.ru',
                  recipient_list=[email],
                  fail_silently=False)
        return redirect('users:log_next')

class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'


def view_code(request):
    form = OneTimeCodeForm()
    return render(request, 'users/log_next.html', {'form': form, 'title': 'Код проверки', })


def log_with_code_view(request):
    username = request.POST['username']
    code = request.POST['code']
    user = User.objects.get(username=username)
    email = User.objects.get(email=user.email)
    if OneTimeCode.objects.filter(code=code, user=user).exists():
        user.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        OneTimeCode.objects.filter(user=user).delete()
        return render(request, 'users/sign_success.html', {'success login': 'Вы будете перенаправлены на страницу ЛК', })
    else:
        return render(request, 'users/signup.html', {'error': 'ошибка ввода имени или пароля', })
    return redirect('users:login')

project/templates/users/log_next.html
{% extends 'base.html' %}

{% block content %}
<h3> {{title}} </h3>

<form method="post" action="{% url 'users:view_code' %}">
    {% csrf_token %}
    {{ error }}
    {{ form.as_p }}

    <input class="btn btn-outline-info" type="submit" value="Войти">
</form>

{% endblock %}

project/templates/users/login.html
{% extends "base.html" %}

{% block content %}
<h2> Войти в систему </h2>
<form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    <table>
    <tr>
        <td>{{ form.username.label_tag }}</td>
        <td>{{ form.username }}</td>
    </tr>
    <tr>
        <td>{{ form.email.label_tag }}</td>
        <td>{{ form.email }}</td>
    </tr>
    <tr>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
    </tr>
    </table>
    <input class="btn btn-outline-primary" mb-5 type="submit" value="Войти">
</form>

<br>
<button> <a href="/users/signup/"> Регистрация </a></button>
{% endblock %}

project/templates/users/logout.html
{% extends "base.html" %}

{% block content %}
<h2> Вы вышли из системы </h2>
{% endblock %}

project/templates/users/sign_success.html
{% extends 'base.html' %}

{% block title %}
SignIn
{% endblock title %}

{% block content %}
<h2>{{ request.user.username }}! </h2>
<h3> Вы успешно зарегистрировались </h3>

{% endblock %}

project/templates/users/signup.html
{% extends "base.html" %}

{% block content %}
<h2> Войти в систему </h2>
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Продолжить">
</form>
{% endblock %}
# Здесь мы использовали автоматически формируемое
# представление формы в виде набора тегов <p>